from flask import Flask, jsonify
import os
import socket

app = Flask(__name__)

@app.route('/')
def home():
    return '''
    <h1>Hello from the Application Servera!</h1>
    <p>This response was generated by <strong>Python/Flask</strong> (Application Server)</p>
    <p>But it was proxied through <strong>Nginx</strong> (Web Server)</p>
    <hr>
    <h2>The Flow:</h2>
    <pre>
    Client Request
         |
         v
    +-------------+
    |   NGINX     |  <-- Web Server (port 80/443)
    |  (Reverse   |      - Handles SSL/TLS
    |   Proxy)    |      - Serves static files
    +-------------+      - Load balancing
         |               - Caching
         v
    +-------------+
    |   Gunicorn  |  <-- Application Server (port 5000)
    |   + Flask   |      - Runs Python code
    |             |      - Business logic
    +-------------+      - Database queries
    </pre>
    '''

@app.route('/api/info')
def info():
    """API endpoint to show server info"""
    return jsonify({
        "message": "Response from Application Server",
        "hostname": socket.gethostname(),
        "server": "Flask + Gunicorn (Application Server)",
        "proxy": "Nginx (Web Server)",
    })

@app.route('/api/compute')
def compute():
    """Simulate some computation that only an app server can do"""
    result = sum(range(1000000))
    return jsonify({
        "task": "Sum of numbers 0-999999",
        "result": result,
        "note": "This computation runs in Python - Nginx can't do this!"
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
